name: "Prep project porter.yml"
description: "Preps the porter.yml with the domains for the project"
inputs:
  repo-name: # id of input
    description: "Name of the project"
    required: true
  token: # id of input
    description: "Github token"
    required: true
  output: # id of input
    description: "Output - branches | config"
    default: config
outputs:
  branches: # id of output
    description: "JSON array of branches"
runs:
  using: "node16"
  main: "index.js"
