name: "Prep project porter.yml"
description: "Preps the porter.yml with the domains for the project"
inputs:
  project-name: # id of input
    description: "Name of the project"
    required: true
runs:
  using: "node16"
  main: "index.js"
