name: "Prep project porter.yml"
description: "Preps the porter.yml with the domains for the project"
inputs:
  project-name: # id of input
    description: "Name of the project"
    required: true
  env: # id of input
    description: "Deployment environment: prod or dev"
    required: true
    default: "dev"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "index.js"
